name: Steve Dimmick
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73928
title: "Pethau dwi'n hoffi ar y we - Things I like on the web"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#645a50'
    - '#241f1e'
    - '#6d3600'
    - '#91887c'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
